# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f445e3e2477ddab54f1bbe68dfe18c98dbb9293f65a269dbe056fdd379fd4b26858f6127e1fe6ad63b5ea98fd98e50e3a8d8d00f9887d183392b73fdef7d9d64

test:
  secret_key_base: 7529949c15b1ae58b0a87e198f6e5064378092b4220771a820291f81a6426ecb464ce0f48d585f8364dbe28dd4296b07c943c76efeb11258c356aec5cf55e719

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
